# Automated testing using appveyor.com

version: 0.2.{build}

image:
- Ubuntu

branches:
  only:
    - master

platform:
  - x64

configuration:
  - Debug

#for:
#  - matrix:
#      only:
#        - image: Ubuntu
#          platform: x64
#          configuration: Debug
install:
  - sudo apt update -qq
  - sudo apt install -y lcov
build_script:
  - make
test_script:
  - make coverage
  - if [ $(grep -cF `printf "\e[1;31m"` build/debug/log/test*.log) != 0 ]; then false; fi
artifacts:
  - path: build/debug/coverage.svg
    name: coverage_shield

